import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState,useEffect } from 'react'
import { Box,Text , Badge,Center,Divider,SimpleGrid,Grid } from '@chakra-ui/react'
import axios from 'axios'
import DataComponent from './conponents/DataConponent'
import CreateFood from './conponents/CreateFood'

const Home: NextPage = () => {

  const [dataApi,setDataApi] = useState([])
    async function getApi() {
      const response = await axios.get('https://localhost:7153/api/Food');
      setDataApi(response.data)
  }
  useEffect(()=>{
    getApi()
  },[dataApi])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Center>
        <Text fontSize='2em'  fontWeight='bold' top="20" mb="7" mt="7">
          Rattakit
          <Badge ml='3' fontSize='1em' colorScheme='green'>
            Test
          </Badge>
        </Text>
      </Center>
      <Divider />
      <Center>
        <SimpleGrid w='75%' columns={1} spacingX='40px' spacingY='20px'>
          <Grid justifyContent='right'>
            <CreateFood eventCreate={getApi} />
          </Grid>
          <Box  p="2" borderWidth='1px' borderRadius='lg' overflow='hidden'>
            <DataComponent items={dataApi} eventData={getApi} />
          </Box>
        </SimpleGrid>
      </Center>
      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home